version: 2.1

jobs:
  build:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Build Docker image
          command: docker build -t myapp:${CIRCLE_SHA1} .

      - run:
          name: Run tests
          command: docker run myapp:${CIRCLE_SHA1} npm test

      - run:
          name: Deploy
          command: docker run -d -p 5000:5000 myapp:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main