name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build-test-push:
    name: Build, Test & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      - name: Run tests inside container
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest npm test

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    name: Deploy to Server
    needs: build-test-push  # Waits for the first job to finish
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-app:latest



# Setup Required  Secrets in GitHub (Settings > Secrets):

# DOCKER_USERNAME: Your Docker Hub username
# DOCKER_PASSWORD: Your Docker Hub password/token
# SERVER_HOST: The IP or domain of your remote server
# SERVER_USER: The SSH username
# SSH_PRIVATE_KEY: The private SSH key for secure connection
