# Example docker-compose.yml:

    version: '3.7'
    services:
        web:
            build: .
            ports:
              - "80:80"
            depends_on:
              - db
        db:
            image: mysql:5.7
            environment:
              MYSQL_ROOT_PASSWORD: example
            volumes:
              - db-data:/var/lib/mysql

    volumes:
    db-data:

    
