stages:
  - build
  - test
  - deploy

variables:
  DOCKER_USERNAME: $CI_DOCKER_USERNAME
  DOCKER_PASSWORD: $CI_DOCKER_PASSWORD

build:
  stage: build
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t myapp:${CI_COMMIT_SHA} .

test:
  stage: test
  script:
    - docker run myapp:${CI_COMMIT_SHA} npm test

deploy:
  stage: deploy
  script:
    - docker run -d -p 5000:5000 myapp:${CI_COMMIT_SHA}
  only:
    - main